from datetime import datetime
from decimal import Decimal
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field

from app.models.enums import (
    BookingItemStatus,
    BookingStatus,
    FareType,
    FlightClassType,
    FlightStatus,
    PolicyDocumentStatus,
    PolicyIngestionStatus,
    PolicyType,
    UserRole,
)


# ============================================================================
# 1. POLICY DOCUMENT METADATA SCHEMAS
# ============================================================================

class PolicyDocumentCreate(BaseModel):
    document_name: str = Field(..., min_length=1, max_length=255, description="Unique human-readable or canonical document name (e.g. 'conditions_of_carriage.md')")
    policy_type: PolicyType = Field(..., description="Category of the policy document")
    version: str = Field(..., min_length=1, max_length=50, description="Semantic or sequential version string (e.g. '1.0', '2026.1')")
    source: str = Field(..., min_length=1, max_length=255, description="Source origin (e.g. 'Customer Service Manual', 'Carrier Terms')")
    source_url: Optional[str] = Field(None, max_length=1024, description="Optional URL or storage path to source artifact")
    content: Optional[str] = Field(None, description="Raw text content of the policy document. If supplied, SHA-256 hash and content length are automatically computed.")
    document_hash: Optional[str] = Field(None, min_length=64, max_length=64, description="Precomputed SHA-256 checksum hex string if content is omitted.")
    effective_from: Optional[datetime] = Field(None, description="When policy becomes active. Defaults to now().")
    effective_until: Optional[datetime] = Field(None, description="Optional policy expiration date.")
    chunk_count: Optional[int] = Field(0, ge=0, description="Number of vector chunks generated by n8n embedding.")
    metadata_info: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Arbitrary structured metadata for ingestion tracking.")
    supersede_previous_active: bool = Field(True, description="If True, automatically marks older ACTIVE versions with the same document_name as SUPERSEDED.")


class PolicyDocumentUpdate(BaseModel):
    status: Optional[PolicyDocumentStatus] = Field(None, description="New lifecycle status of policy document")
    ingestion_status: Optional[PolicyIngestionStatus] = Field(None, description="Ingestion progress status (e.g. COMPLETED after Pinecone upsert)")
    source_url: Optional[str] = Field(None, max_length=1024)
    effective_until: Optional[datetime] = None
    chunk_count: Optional[int] = Field(None, ge=0)
    metadata_info: Optional[Dict[str, Any]] = None


class PolicyDocumentResponse(BaseModel):
    id: UUID
    document_name: str
    policy_type: PolicyType
    version: str
    source: str
    source_url: Optional[str] = None
    document_hash: str
    status: PolicyDocumentStatus
    ingestion_status: PolicyIngestionStatus
    effective_from: datetime
    effective_until: Optional[datetime] = None
    content_length: Optional[int] = None
    chunk_count: int
    metadata_info: Dict[str, Any]
    retrieved_at: Optional[datetime] = None
    created_by: Optional[UUID] = None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class PaginatedPolicyDocumentResponse(BaseModel):
    items: List[PolicyDocumentResponse]
    total: int
    page: int
    page_size: int
    total_pages: int


# ============================================================================
# 2. CHANGE DETECTION SCHEMAS (FOR N8N INGESTION AGENTS)
# ============================================================================

class PolicyChangeDetectionItem(BaseModel):
    document_name: str = Field(..., description="Canonical document name to compare")
    content: Optional[str] = Field(None, description="Raw content to hash using SHA-256")
    document_hash: Optional[str] = Field(None, description="Precalculated SHA-256 hash")
    version: Optional[str] = Field(None, description="Version string candidate")


class PolicyChangeDetectionRequest(BaseModel):
    documents: List[PolicyChangeDetectionItem] = Field(..., min_length=1, description="List of candidate documents to evaluate for embedding changes")


class PolicyDocumentChangeResult(BaseModel):
    document_name: str
    version: Optional[str] = None
    supplied_hash: str
    change_status: str = Field(..., description="NEW_DOCUMENT | CONTENT_CHANGED | UNCHANGED | SUPERSEDED")
    requires_embedding: bool
    existing_document_id: Optional[UUID] = None
    existing_version: Optional[str] = None
    existing_status: Optional[PolicyDocumentStatus] = None
    existing_ingestion_status: Optional[PolicyIngestionStatus] = None
    reason: str


class PolicyChangeDetectionResponse(BaseModel):
    results: List[PolicyDocumentChangeResult]
    total_evaluated: int
    requires_embedding_count: int


# ============================================================================
# 3. AUTHORITATIVE BOOKING RAG CONTEXT SCHEMAS
# ============================================================================

class BookingFact(BaseModel):
    id: UUID
    booking_reference: str
    status: BookingStatus
    total_amount: Decimal
    currency: str
    hold_expires_at: Optional[datetime] = None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class PassengerFact(BaseModel):
    id: UUID
    name: str
    email: str
    role: UserRole

    model_config = ConfigDict(from_attributes=True)


class FlightFact(BaseModel):
    id: UUID
    flight_number: str
    origin: str
    destination: str
    departure_at: datetime
    arrival_at: datetime
    status: FlightStatus

    model_config = ConfigDict(from_attributes=True)


class FareRuleSnapshotFact(BaseModel):
    fare_rule_id: Optional[str] = None
    fare_type: FareType
    class_type: FlightClassType
    price: Optional[Decimal] = None
    currency: str
    refundable: bool
    credit_only: bool
    changes_allowed: bool
    seat_selection_allowed: bool
    cancellation_cutoff_minutes: int
    snapshotted_at: Optional[datetime] = None


class BookingItemFact(BaseModel):
    id: UUID
    seat_id: UUID
    seat_number: Optional[str] = None
    passenger_name: str
    class_type: FlightClassType
    fare_type: FareType
    price: Decimal
    currency: str
    status: BookingItemStatus
    fare_rule_snapshot: FareRuleSnapshotFact


class BookingPolicyContextFact(BaseModel):
    fare_type: FareType
    refundable: bool
    credit_only: bool
    changes_allowed: bool
    seat_selection_allowed: bool
    cancellation_cutoff_minutes: int
    cancellation_deadline: Optional[datetime] = None
    hours_until_departure: Optional[float] = None
    is_before_cancellation_cutoff: bool
    is_cancellation_allowed: bool
    policy_summary: str


class BookingRAGContextResponse(BaseModel):
    booking: BookingFact
    passenger: PassengerFact
    flight: FlightFact
    items: List[BookingItemFact]
    policy_context: BookingPolicyContextFact
    retrieved_at: datetime
